- name: demo on loops
  hosts: localhost
  connection: local
  tasks:

    - name: print loop items
      ansible.builtin.debug:
        msg: fruit name - {{ }}
      loop:
        - apple
        - bannana
        - pine
        - grape
        - papaya
        - guava
        - kiwi
        - mango