- name: demo on contions
  hosts: localhost
  connection: local
  tasks:

    - name: register variable
      ansible.builtin.shell: uptime
      register: output

    - name: print registered value
      ansible.builtin.debug:
        msg: "{{ output.stdout | split(' ') }}"

    - name: print registered value using join to convert list to single string
      ansible.builtin.debug:
        msg: "{{ output.stdout_lines | join(' ') | split(' ') }}"