- name: Demo variafbles declaration
  hosts: all
  vars:
    URL: example.com
  tasks:

    - name: print URL variable
      ansible.builtin.debug:
        msg: "{{ URL }}"

    - name: print URL variable
      ansible.builtin.debug:
        msg: URL is {{ URL }}